config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path("", include("tryread.home.urls", namespace="home")),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),

    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("tryread.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("read/", include("read.urls", namespace="read")),
    path("writer/", include("tryread.writer.urls", namespace="writer")),

] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

tryread/home/urls.py
from django.urls import path

from . import views

app_name = "home"
urlpatterns = [
    path(
        "",
        view=views.HomeTemplateView.as_view(),
        name="home"
    ),
    path(
        "landing/",
        view=views.LandingTemplateView.as_view(),
        name="landing"
    ),
    path(
        "landing/reader/",
        view=views.LandingReaderTemplateView.as_view(),
        name="landing-reader"
    ),
    path(
        "landing/writer/",
        view=views.LandingWriterTemplateView.as_view(),
        name="landing-writer"
    ),

]

tryread/read/urls.py
from django.urls import path

from . import views

app_name = "read"
urlpatterns = [
    path("", view=views.ReadBooksListView.as_view(), name="books"),
    path(
        '<slug:slug_book>/<int:pk_book>/',
        view=views.ReadBookDetailView.as_view(),
        name='book-detail'
    ),
    path(
        '<slug:slug_book>/<int:pk_book>/<int:pk_chapter>/',
        view=views.ReadChapterDetailView.as_view(),
        name='chapter-detail'
    ),

]

tryread/users/urls.py
from django.urls import path

from . import views

app_name = "users"
urlpatterns = [
    path("", view=views.UserListView.as_view(), name="list"),
    path("~redirect/", view=views.UserRedirectView.as_view(), name="redirect"),
    path("~update/", view=views.UserUpdateView.as_view(), name="update"),
    path(
        "<str:username>",
        view=views.UserDetailView.as_view(),
        name="detail",
    ),
]

tryread/writer/urls.py
from django.urls import path

from . import views

app_name = "writer"
urlpatterns = [
    path(
        '',
        view=views.WriterTemplateView.as_view(),
        name='writer'
    ),
    path(
        'book-create/',
        view=views.WriterBookCreateView.as_view(),
        name='book-create'
    ),
    path(
        'books',
        view=views.WriterBooksListView.as_view(),
        name='books'
    ),
    path(
        '<slug:slug_book>/<int:pk_book>/',
        view=views.WriterBookDetailView.as_view(),
        name='book'
    ),
    path(
        '<slug:slug_book>/<int:pk_book>/chapter-create/',
        view=views.WriterChapterCreateView.as_view(),
        name='chapter-create'
    ),
    path(
        '<slug:slug_book>/<slug:slug_chapter>/<int:pk_chapter>/',
        view=views.WriterChapterDetailView.as_view(),
        name='chapter'
    ),
    path(
        '<slug:slug_book>/<slug:slug_chapter>/update/<int:pk_chapter>/',
        view=views.WriterChapterUpdateView.as_view(),
        name='chapter-update'
    ),
    path(
        '<slug:slug_book>/<slug:slug_chapter>/preview/<int:pk_chapter>/',
        view=views.WriterChapterPreviewUpdateView.as_view(),
        name='chapter-preview'
    ),
    path(
        '<slug:slug_book>/<slug:slug_chapter>/<int:pk_chapter>/text-create/',
        view=views.WriterTextCreateView.as_view(),
        name='text-create'
    ),
    path(
        '<slug:slug_book>/<slug:slug_chapter>/<int:pk_chapter>/text-delete/<int:pk_text>/',
        view=views.WriterTextDeleteView.as_view(),
        name='text-delete'
    ),
    path(
        '<slug:slug_book>/<slug:slug_chapter>/<int:pk_chapter>/update-text/<int:pk_text>/',
        view=views.WriterTextUpdateView.as_view(),
        name='text-update'
    ),

    path(
        '<slug:slug_book>/<slug:slug_chapter>/<int:pk_chapter>/add-picture/',
        view=views.WriterPictureCreateView.as_view(),
        name='picture-create'
    ),
    path(
        '<slug:slug_book>/<slug:slug_chapter>/<int:pk_chapter>/delete-picture/<int:pk_picture>/',
        view=views.WriterPictureDeleteView.as_view(),
        name='picture-delete'
    ),
    path(
        '<slug:slug_book>/<slug:slug_chapter>/<int:pk_chapter>/picture-update/<int:pk_picture>/',
        view=views.WriterPictureUpdateView.as_view(),
        name='picture-update'
    ),

]

tryread/home/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import TemplateView


class HomeTemplateView(TemplateView):
    template_name = 'home/home.html'

    def get(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('home:landing')
        else:
            return super(HomeTemplateView, self).get(request, *args, **kwargs)



class LandingTemplateView(TemplateView):
    template_name = 'home/landing.html'

class LandingReaderTemplateView(TemplateView):
    template_name = 'home/landing-reader.html'

class LandingWriterTemplateView(TemplateView):
    template_name = 'home/landing-writer.html'

tryread/read/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView
from django.views.generic.edit import FormMixin

from books.forms import BookFiltersForm
from books.models import Book, Chapter
from tryread.users.models import User
from writer.views import PicturesAndTextAsElementsMixin


class ReadBooksListView(LoginRequiredMixin, FormMixin, ListView):
    context_object_name = 'books'
    form_class = BookFiltersForm
    model = Book
    template_name = "read/books.html"

    def get_queryset(self):
        queryset = Book.objects.only('pk', 'author', 'title', 'slug')
        queryset = queryset.select_related('author')
        if self.request.GET.get('author'):
            author_submited_by_user = self.request.GET.get('author')
            if not author_submited_by_user == '':
                queryset = queryset.filter(author__username = author_submited_by_user)
        if self.request.GET.get('title'):
            title_submited_by_user = self.request.GET.get('title')
            if not title_submited_by_user == '':
                queryset = queryset.filter(title = title_submited_by_user)
        if self.request.GET.get('category'):
            category_choosed_by_user = self.request.GET.get('category')
            if not category_choosed_by_user == 'ALL':
                queryset = queryset.filter(category = category_choosed_by_user)
        return queryset




class ReadBookDetailView(LoginRequiredMixin, DetailView):
    context_object_name = 'book'
    model = Book
    pk_url_kwarg = 'pk_book'
    template_name = "read/book.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        book = self.object
        chapters = book.chapters.all()
        context['chapters'] = chapters
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.select_related('author')
        return queryset


class ReadChapterDetailView(LoginRequiredMixin, PicturesAndTextAsElementsMixin, DetailView):
    context_object_name = 'chapter'
    model = Chapter
    pk_url_kwarg = 'pk_chapter'
    template_name = "read/chapter.html"

tryread/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ["name"]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"

tryread/writer/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, TemplateView, UpdateView

from itertools import chain

from books.forms import BookForm, ChapterForm, ChapterPublishForm, PictureForm, TextForm
from books.models import Book, Chapter, Picture, Text

class BooksWrittenByCurrentUserMixin():
    def get_queryset(self):
        queryset = Book.objects.all().filter(author=self.request.user)
        return queryset

class WriterBookCreateView(LoginRequiredMixin, CreateView):
    model = Book
    form_class = BookForm
    template_name = "writer/add-book.html"
    success_url = '/writer/'

    def form_valid(self, form):
        form.instance.author = self.request.user
        from django.core.mail import EmailMessage
        email = EmailMessage(
            'Hello',
            'Body goes here',
            ['r.szymansky@gmail.com'],

        )
        email.send()
        return super().form_valid(form)


class WriterBookDetailView(LoginRequiredMixin, BooksWrittenByCurrentUserMixin, DetailView):
    context_object_name = 'book'
    model = Book
    pk_url_kwarg = 'pk_book'
    template_name = 'writer/book.html'

    def get_context_data(self, **kwargs):
        """Insert the single object into the context dict."""
        context = {}

        if self.object:
            context['object'] = self.object
            context['chapters'] = Chapter.objects.all().filter(book=self.object)
            context_object_name = self.get_context_object_name(self.object)
            if context_object_name:
                context[context_object_name] = self.object
        context.update(kwargs)
        return super().get_context_data(**context)


class WriterBooksListView(LoginRequiredMixin, BooksWrittenByCurrentUserMixin, ListView):
    context_object_name = 'books'
    model = Book
    template_name = 'writer/books.html'


class WriterChapterCreateView(LoginRequiredMixin, CreateView):
    model = Chapter
    form_class = ChapterForm
    template_name = "writer/add-chapter.html"

    def form_valid(self, form):
        self.book = Book.objects.get(pk = self.kwargs.get('pk_book'))
        if self.book in Book.objects.all().filter(author=self.request.user):
            print('_'*15, ' to jest book napisana przez autora')

        form.instance.book = self.book
        return super().form_valid(form)

    def get_success_url(self):
        pk_book = self.kwargs.get('pk_book')
        slug_book = self.book.slug
        return reverse('writer:book', kwargs={'pk_book': pk_book, 'slug_book': slug_book})

class WriterChapterUpdateView(LoginRequiredMixin, UpdateView):
    context_object_name = 'chapter'
    form_class = ChapterForm
    model = Chapter
    pk_url_kwarg = 'pk_chapter'
    template_name = "writer/chapter-update.html"

    def get_success_url(self):
        pk_chapter = self.kwargs.get('pk_chapter')
        slug_chapter = self.kwargs.get('slug_chapter')
        slug_book = self.kwargs.get('slug')
        return reverse('writer:chapter',
            kwargs={
                'slug_book': slug_book,
                'slug_chapter': slug_chapter,
                'pk_chapter': pk_chapter
            }
        )

class PicturesAndTextAsElementsMixin():
    def get_context_data(self, **kwargs):
        """Insert the single object into the context dict."""
        context = {}

        if self.object:
            context['object'] = self.object
            pictures = Picture.objects.all().filter(chapter = self.object)
            texts = Text.objects.all().filter(chapter = self.object)
            list_of_elements = sorted(
                chain(pictures, texts),
                key=lambda element: element.created, reverse=False)
            context['elements'] = list_of_elements
            context_object_name = self.get_context_object_name(self.object)
            if context_object_name:
                context[context_object_name] = self.object
        context.update(kwargs)
        return super().get_context_data(**context)


class WriterChapterDetailView(LoginRequiredMixin, PicturesAndTextAsElementsMixin, DetailView):
    context_object_name = 'chapter'
    model = Chapter
    pk_url_kwarg = 'pk_chapter'
    template_name = 'writer/chapter.html'


class WriterChapterPreviewUpdateView(LoginRequiredMixin, PicturesAndTextAsElementsMixin, UpdateView):
    form_class = ChapterPublishForm
    model = Chapter
    pk_url_kwarg = 'pk_chapter'
    template_name = 'writer/chapter-preview.html'

    def form_valid(self, form):
        chapter = self.object
        if chapter.published:
            form.instance.published = False
        else:
            form.instance.published = True
        return super().form_valid(form)

    def get_success_url(self):
        pk_chapter = self.kwargs.get('pk_chapter')
        chapter = Chapter.objects.get(pk = pk_chapter)
        pk_book = chapter.book.pk
        return reverse('writer:book',
            kwargs={
                'slug_book': self.kwargs.get("slug_book"),
                'pk_book': pk_book,
            }
        )


class WriterTemplateView(LoginRequiredMixin, TemplateView):
    template_name = 'writer/writer.html'

class GetBackToChapterMixin():

    def get_success_url(self):
        return reverse('writer:chapter',
            kwargs={
                'slug_book': self.kwargs.get("slug_book"),
                'slug_chapter': self.kwargs.get("slug_chapter"),
                'pk_chapter': self.kwargs.get("pk_chapter"),
            }
        )

class WriterPictureCreateView(LoginRequiredMixin, GetBackToChapterMixin, CreateView):
    model = Picture
    form_class = PictureForm
    template_name = 'writer/picture-create.html'

    def form_valid(self, form):
        self.chapter = Chapter.objects.get(pk = self.kwargs.get('pk_chapter'))
        form.instance.chapter = self.chapter
        return super().form_valid(form)


class WriterPictureDeleteView(LoginRequiredMixin, GetBackToChapterMixin, DeleteView):
    context_object_name = 'picture'
    form_class = PictureForm
    model = Picture
    pk_url_kwarg = 'pk_picture'
    template_name = 'writer/picture-delete.html'


class WriterPictureUpdateView(LoginRequiredMixin, GetBackToChapterMixin, UpdateView):
    model = Picture
    form_class = PictureForm
    pk_url_kwarg = 'pk_picture'
    template_name = 'writer/picture-update.html'

class WriterTextCreateView(LoginRequiredMixin, GetBackToChapterMixin, CreateView):
    model = Text
    form_class = TextForm
    template_name = "writer/add-text.html"

    def form_valid(self, form):
        self.chapter = Chapter.objects.get(pk = self.kwargs.get('pk_chapter'))
        form.instance.chapter = self.chapter
        return super().form_valid(form)


    def get_context_data(self, **kwargs):
        """Insert the single object into the context dict."""
        context = {}

        if self.object:
            context['object'] = self.object
            context['chapter'] = self.chapter
            context_object_name = self.get_context_object_name(self.object)
            if context_object_name:
                context[context_object_name] = self.object
        context.update(kwargs)
        return super().get_context_data(**context)


class WriterTextDeleteView(LoginRequiredMixin, GetBackToChapterMixin, DeleteView):
    form_class = TextForm
    model = Text
    pk_url_kwarg = 'pk_text'
    template_name = "writer/text-delete.html"


class WriterTextUpdateView(LoginRequiredMixin, GetBackToChapterMixin, UpdateView):
    form_class = TextForm
    model = Text
    pk_url_kwarg = 'pk_text'
    template_name = "writer/text-update.html"

tryread/templates/writer/add-book.html
{% extends "base-my.html" %}
{% block content %}


<div class="container py-5">
  <h1>Add new book</h1>
  <p>Hello dear Author</p>
  <form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
  </form>



  <form>
    <div class="form-group">
      <label for="exampleFormControlTextarea1">Title</label>
      <input class="form-control" type="text" placeholder="Enter title of the book here">
    </div>
    <div class="form-group">
      <label for="exampleFormControlTextarea1">Subtitle</label>
      <input class="form-control" type="text" placeholder="Enter second title here (optional)">
    </div>
    <div class="form-group">
      <label for="exampleFormControlTextarea1">Description</label>
      <textarea class="form-control" id="exampleFormControlTextarea1" rows="5">Enter short description here</textarea>
    </div>
    <div class="form-group">
      <label for="xampleFormControlSelect1">Category</label>
      <select class="form-control" id="exampleFormControlSelect1">

        <option>Romance</option>
        <option>Thriller</option>
        <option>Historic</option>
        <option>Life</option>
        <option>Drama</option>
      </select>
    </div>
    <div class="form-group">
      <label for="exampleFormControlTags">Tags</label>
      <input class="form-control" type="text" placeholder="Enter tags here">
    </div>
    <p>
      <button class="btn btn-outline-secondary" type="button" data-toggle="collapse" data-target="#collapseFilters" aria-expanded="false" aria-controls="collapseExample">
        Filters
      </button>
    </p>
    <div class="collapse" id="collapseFilters">
      <div class="card card-body">
        <div class="form-check">
          <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
          <label class="form-check-label" for="defaultCheck1">
            Default checkbox
          </label>
        </div>
        <div class="form-check">
          <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
          <label class="form-check-label" for="defaultCheck1">
            Default checkbox
          </label>
        </div>
        <div class="form-check">
          <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
          <label class="form-check-label" for="defaultCheck1">
            Default checkbox
          </label>
        </div>
        <div class="form-check">
          <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
          <label class="form-check-label" for="defaultCheck1">
            Default checkbox
          </label>
        </div>
        <div class="form-check">
          <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
          <label class="form-check-label" for="defaultCheck1">
            Default checkbox
          </label>
        </div>
      </div>
      <br><br>
    </div>

  </form>
  <br><br>



</div>


{% endblock content %}

tryread/templates/writer/add-chapter.html
{% extends "base-my.html" %}
{% block content %}


<div class="container py-5">
  <h1>Add Chapter</h1>
  <p>Hello dear Author</p>
  <form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
  </form>


  <br><br>



</div>


{% endblock content %}

tryread/templates/writer/add-text.html
{% extends "base-my.html" %}
{% block content %}


<div class="container py-5">
  <h1>Add Text</h1>
  {{ object }}
  <p>You're adding text section to {{ chapter }} in {{ chapter.book }}</p>
  <form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
  </form>


  <br><br>



</div>


{% endblock content %}

tryread/templates/writer/book.html
{% extends "base-my.html" %}
{% block content %}


<div class="container py-5">
  <h1>{{ book.title }}</h1>
  <p>by {{ book.author }}</p>
  <p>Subtitle: {{ book.subtitle }}</p>
  <p>Description: {{ book.description }}</p>
  <p>Tags: {{ book.tags }}</p>
  <br><br>
  <p>Chapters:</p>
  {% for chapter in chapters %}
    <a href="{% url 'writer:chapter' slug_book=book.slug slug_chapter=chapter.slug pk_chapter=chapter.pk %}">
      {{ chapter.nr }}. {{ chapter }}
    </a>
    {% if chapter.published %}
      <p class="text-success">published</p>
    {% else %}
      <p class="text-danger">not published</p>
    {% endif %}


  {% endfor %}
  <br><br>


  <a href="{% url 'writer:chapter-create' slug_book=book.slug pk_book=book.pk %}" class="btn btn-lg btn-outline-dark" role="button">New chapter</a>

</div>


{% endblock content %}

tryread/templates/writer/books.html
{% extends "base-my.html" %}
{% block content %}


<div class="container py-5">
  <h1>Your books</h1>
  {% for book in books %}
    <a href="{% url 'writer:book' slug_book=book.slug pk_book=book.pk %}"><p>Title: {{ book.title }}, Slug: {{ book.slug }}</p></a>
  {% endfor %}

</div>


{% endblock content %}

tryread/templates/writer/chapter-preview.html
{% extends "base-my.html" %}
{% block content %}


<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="container py-5">
  <h1>Chapter {{ chapter.nr }}. {{ chapter.title }}</h1>
  <p>from {{ chapter.book }} by {{ view.request.user }}</p>
  <br><br>
  {% for element in elements %}
    {% if element.picture %}
      <img src="{{ element.picture.url }}" class="img-thumbnail"/>
    {% elif element.text %}
      <p>{{ element.text|linebreaks }}</p>
      <p class="font-bigger">{{ element.text|linebreaks }}</p>
    {% endif %}
  {% endfor %}
  <br><br>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <div class="text-center">
      {% if chapter.published %}
        <input type="submit" class="btn btn-lg btn-outline-danger" role="button" value="Do Not Publish" />
      {% endif %}
      {% if not chapter.published %}
        <input type="submit" class="btn btn-lg btn-outline-success" role="button" value="Publish" />
      {% endif %}
    </div>
  </form>
  <br><br>
  <div class="fb-share-button" data-href="https://www.tryread.com/" data-layout="button" data-size="large" data-mobile-iframe="true"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fwww.tryread.com%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Share</a></div>


</div>



{% endblock content %}

tryread/templates/writer/chapter-update.html
{% extends "base-my.html" %}
{% block content %}


<div class="container py-5">
  <h1>Update Chapter</h1>
  <form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
  </form>


  <br><br>



</div>


{% endblock content %}

tryread/templates/writer/chapter.html
{% extends "base-my.html" %}
{% block content %}


<div class="container py-5">
  <h1>Chapter {{ chapter.nr }}. {{ chapter.title }}</h1>
  <p>from book {{ chapter.book }}</p>
  <br><br>
  <div class="text-center">
    <a class="btn btn-lg btn-outline-dark" href="{% url 'writer:chapter-update' slug_book=chapter.book.slug slug_chapter=chapter.slug pk_chapter=chapter.pk %}">Edit</a>
  </div>
  <br><br>
  <hr>

  {% for element in elements %}
    {% if element.picture %}
      <img src="{{ element.picture.url }}" class="img-thumbnail"/>
      <br><br>
      <div class="text-center">
        <a class="btn btn-lg btn-outline-dark" href="{% url 'writer:picture-update' slug_book=chapter.book.slug slug_chapter=chapter.slug pk_chapter=chapter.pk pk_picture=element.pk %}">Edit</a>
        <a class="btn btn-lg btn-outline-dark" href="{% url 'writer:picture-delete' slug_book=chapter.book.slug slug_chapter=chapter.slug pk_chapter=chapter.pk pk_picture=element.pk %}">Delete</a>
      </div>
      <br><br>
      <hr>
    {% elif element.text %}
      <p>{{ element.text|linebreaks }}</p>
      <br><br>
      <div class="text-center">
        <a class="btn btn-lg btn-outline-dark" href="{% url 'writer:text-update' slug_book=chapter.book.slug slug_chapter=chapter.slug pk_chapter=chapter.pk pk_text=element.pk %}">Edit</a>
        <a class="btn btn-lg btn-outline-dark" href="{% url 'writer:text-delete' slug_book=chapter.book.slug slug_chapter=chapter.slug pk_chapter=chapter.pk pk_text=element.pk %}">Delete</a>
      </div>
      <br><br>
      <hr>
    {% endif %}

  {% endfor %}

  <br><br>
  <div class="text-center">
    <a class="btn btn-lg btn-outline-dark" href="{% url 'writer:text-create' slug_book=chapter.book.slug slug_chapter=chapter.slug pk_chapter=chapter.pk %}">+ Text</a>
    <a class="btn btn-lg btn-outline-dark" href="{% url 'writer:picture-create' slug_book=chapter.book.slug slug_chapter=chapter.slug pk_chapter=chapter.pk %}">+ Picture</a>
    <a class="btn btn-lg btn-outline-dark" href="{% url 'writer:chapter-preview' slug_book=chapter.book.slug slug_chapter=chapter.slug pk_chapter=chapter.pk %}">Preview</a>
  </div>


</div>


{% endblock content %}

tryread/templates/writer/picture-create.html
{% extends "base-my.html" %}
{% block content %}


<div class="container py-5">
  <h1>Add Picture</h1>
  {{ object }}
  <p>You're adding picture to {{ chapter }} in {{ chapter.book }}</p>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
  </form>


  <br><br>



</div>


{% endblock content %}

tryread/templates/writer/section-update.html
{% extends "base-my.html" %}
{% block content %}


{% include "_nav2.html" %}
<div class="container py-5">
  <h1>Section update.</h1>
  <form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
  </form>

</div>


{% endblock content %}

tryread/templates/writer/writer.html
{% extends "base-my.html" %}
{% block content %}


<div class="container py-5">
  <h1>Writer's dashboard</h1>
  <p>{{ view.request.user }}</p>

  <a href="{% url 'writer:books' %}" class="btn btn-lg btn-outline-dark" role="button">Your books</a>
  <br><br>
  <a href="{% url 'writer:book-create' %}" class="btn btn-lg btn-outline-dark" role="button">New book</a>
  <br><br>
  <a href="#" class="btn btn-lg btn-outline-dark" role="button">Rates</a>
  <br><br>
  <a href="#" class="btn btn-lg btn-outline-dark" role="button">Messages</a>
  <br><br>
  <a href="#" class="btn btn-lg btn-outline-dark" role="button">Fans</a>
  <br><br>
  <a href="#" class="btn btn-lg btn-outline-dark" role="button">Money</a>


</div>


{% endblock content %}