config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path("", include("tryread.home.urls", namespace="home")),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),

    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("tryread.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("read/", include("read.urls", namespace="read")),
    path("writer/", include("tryread.writer.urls", namespace="writer")),

] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

tryread/home/urls.py
from django.urls import path

from . import views

app_name = "home"
urlpatterns = [
    path(
        "",
        view=views.HomeTemplateView.as_view(),
        name="home"
    ),
    path(
        "landing/",
        view=views.LandingTemplateView.as_view(),
        name="landing"
    ),
    path(
        "landing/reader/",
        view=views.LandingReaderTemplateView.as_view(),
        name="landing-reader"
    ),
    path(
        "landing/writer/",
        view=views.LandingWriterTemplateView.as_view(),
        name="landing-writer"
    ),

]

tryread/read/urls.py
from django.urls import path

from . import views

app_name = "read"
urlpatterns = [
    path("", view=views.ReadBooksListView.as_view(), name="books"),
    path(
        '<slug:slug_book>/<int:pk_book>/',
        view=views.ReadBookDetailView.as_view(),
        name='book-detail'
    ),
    path(
        '<slug:slug_book>/<int:pk_book>/<int:pk_chapter>/',
        view=views.ReadChapterDetailView.as_view(),
        name='chapter-detail'
    ),

]

tryread/users/urls.py
from django.urls import path

from . import views

app_name = "users"
urlpatterns = [
    path("", view=views.UserListView.as_view(), name="list"),
    path("~redirect/", view=views.UserRedirectView.as_view(), name="redirect"),
    path("~update/", view=views.UserUpdateView.as_view(), name="update"),
    path(
        "<str:username>",
        view=views.UserDetailView.as_view(),
        name="detail",
    ),
]

tryread/read/models.py
from django.db import models

# Create your models here.

tryread/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_("Name of User"), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

tryread/writer/models.py
from django.db import models

tryread/books/forms.py
from django import forms
#from django.forms import ModelForm, HiddenInput
from .models import Book, Chapter, Picture, Text

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = [
            'title',
            'subtitle',
            'description',
            'category',
            'tags',
        ]

class BookFiltersForm(forms.Form):
    ALL = 'ALL'
    ROMANCE = 'ROM'
    THRILLER = 'THR'
    MYSTERY = 'MYS'
    LIFE = 'LIF'
    DRAMA = 'DRA'
    HISTORIC = 'HIS'
    BIOGRAPHY = 'BIO'
    KIDS = 'KID'
    CATEGORIES = (
        (ALL, 'All'),
        (ROMANCE, 'Romance'),
        (THRILLER, 'Thriller'),
        (MYSTERY, 'Mystery'),
        (LIFE, 'Life'),
        (DRAMA, 'Drama'),
        (HISTORIC, 'Historic'),
        (BIOGRAPHY, 'Biography'),
        (KIDS, 'Kids'),)
    author = forms.CharField(max_length=150, required=False)
    title = forms.CharField(max_length=250, required=False)
    category = forms.ChoiceField(choices=CATEGORIES,)
    #tags = forms.CharField(max_length=250, required=False)


class ChapterForm(forms.ModelForm):
    class Meta:
        model = Chapter
        fields = [
            'nr',
            'title',
        ]

class ChapterPublishForm(forms.ModelForm):
    class Meta:
        model = Chapter
        fields = [
            'published',
        ]
        widgets = {'published': forms.HiddenInput()}

class PictureForm(forms.ModelForm):
    class Meta:
        model = Picture
        fields = [
            'picture',
        ]

class TextForm(forms.ModelForm):
    class Meta:
        model = Text
        fields = [
            'text',
        ]

tryread/home/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import TemplateView


class HomeTemplateView(TemplateView):
    template_name = 'home/home.html'

    def get(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('home:landing')
        else:
            return super(HomeTemplateView, self).get(request, *args, **kwargs)



class LandingTemplateView(TemplateView):
    template_name = 'home/landing.html'

class LandingReaderTemplateView(TemplateView):
    template_name = 'home/landing-reader.html'

class LandingWriterTemplateView(TemplateView):
    template_name = 'home/landing-writer.html'

tryread/read/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView
from django.views.generic.edit import FormMixin

from books.forms import BookFiltersForm
from books.models import Book, Chapter
from tryread.users.models import User
from writer.views import PicturesAndTextAsElementsMixin


class ReadBooksListView(LoginRequiredMixin, FormMixin, ListView):
    context_object_name = 'books'
    form_class = BookFiltersForm
    model = Book
    template_name = "read/books.html"

    def get_queryset(self):
        queryset = Book.objects.only('pk', 'author', 'title', 'slug')
        queryset = queryset.select_related('author')
        if self.request.GET.get('author'):
            author_submited_by_user = self.request.GET.get('author')
            if not author_submited_by_user == '':
                queryset = queryset.filter(author__username = author_submited_by_user)
        if self.request.GET.get('title'):
            title_submited_by_user = self.request.GET.get('title')
            if not title_submited_by_user == '':
                queryset = queryset.filter(title = title_submited_by_user)
        if self.request.GET.get('category'):
            category_choosed_by_user = self.request.GET.get('category')
            if not category_choosed_by_user == 'ALL':
                queryset = queryset.filter(category = category_choosed_by_user)
        return queryset




class ReadBookDetailView(LoginRequiredMixin, DetailView):
    context_object_name = 'book'
    model = Book
    pk_url_kwarg = 'pk_book'
    template_name = "read/book.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        book = self.object
        chapters = book.chapters.all()
        context['chapters'] = chapters
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.select_related('author')
        return queryset


class ReadChapterDetailView(LoginRequiredMixin, PicturesAndTextAsElementsMixin, DetailView):
    context_object_name = 'chapter'
    model = Chapter
    pk_url_kwarg = 'pk_chapter'
    template_name = "read/chapter.html"

tryread/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ["name"]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"

tryread/writer/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, TemplateView, UpdateView

from itertools import chain

from books.forms import BookForm, ChapterForm, ChapterPublishForm, PictureForm, TextForm
from books.models import Book, Chapter, Picture, Text

class BooksWrittenByCurrentUserMixin():
    def get_queryset(self):
        queryset = Book.objects.all().filter(author=self.request.user)
        return queryset

class WriterBookCreateView(LoginRequiredMixin, CreateView):
    model = Book
    form_class = BookForm
    template_name = "writer/add-book.html"
    success_url = '/writer/'

    def form_valid(self, form):
        form.instance.author = self.request.user
        from django.core.mail import EmailMessage
        email = EmailMessage(
            'Hello',
            'Body goes here',
            ['r.szymansky@gmail.com'],

        )
        email.send()
        return super().form_valid(form)


class WriterBookDetailView(LoginRequiredMixin, BooksWrittenByCurrentUserMixin, DetailView):
    context_object_name = 'book'
    model = Book
    pk_url_kwarg = 'pk_book'
    template_name = 'writer/book.html'

    def get_context_data(self, **kwargs):
        """Insert the single object into the context dict."""
        context = {}

        if self.object:
            context['object'] = self.object
            context['chapters'] = Chapter.objects.all().filter(book=self.object)
            context_object_name = self.get_context_object_name(self.object)
            if context_object_name:
                context[context_object_name] = self.object
        context.update(kwargs)
        return super().get_context_data(**context)


class WriterBooksListView(LoginRequiredMixin, BooksWrittenByCurrentUserMixin, ListView):
    context_object_name = 'books'
    model = Book
    template_name = 'writer/books.html'


class WriterChapterCreateView(LoginRequiredMixin, CreateView):
    model = Chapter
    form_class = ChapterForm
    template_name = "writer/add-chapter.html"

    def form_valid(self, form):
        self.book = Book.objects.get(pk = self.kwargs.get('pk_book'))
        if self.book in Book.objects.all().filter(author=self.request.user):
            print('_'*15, ' to jest book napisana przez autora')

        form.instance.book = self.book
        return super().form_valid(form)

    def get_success_url(self):
        pk_book = self.kwargs.get('pk_book')
        slug_book = self.book.slug
        return reverse('writer:book', kwargs={'pk_book': pk_book, 'slug_book': slug_book})

class WriterChapterUpdateView(LoginRequiredMixin, UpdateView):
    context_object_name = 'chapter'
    form_class = ChapterForm
    model = Chapter
    pk_url_kwarg = 'pk_chapter'
    template_name = "writer/chapter-update.html"

    def get_success_url(self):
        pk_chapter = self.kwargs.get('pk_chapter')
        slug_chapter = self.kwargs.get('slug_chapter')
        slug_book = self.kwargs.get('slug')
        return reverse('writer:chapter',
            kwargs={
                'slug_book': slug_book,
                'slug_chapter': slug_chapter,
                'pk_chapter': pk_chapter
            }
        )

class PicturesAndTextAsElementsMixin():
    def get_context_data(self, **kwargs):
        """Insert the single object into the context dict."""
        context = {}

        if self.object:
            context['object'] = self.object
            pictures = Picture.objects.all().filter(chapter = self.object)
            texts = Text.objects.all().filter(chapter = self.object)
            list_of_elements = sorted(
                chain(pictures, texts),
                key=lambda element: element.created, reverse=False)
            context['elements'] = list_of_elements
            context_object_name = self.get_context_object_name(self.object)
            if context_object_name:
                context[context_object_name] = self.object
        context.update(kwargs)
        return super().get_context_data(**context)


class WriterChapterDetailView(LoginRequiredMixin, PicturesAndTextAsElementsMixin, DetailView):
    context_object_name = 'chapter'
    model = Chapter
    pk_url_kwarg = 'pk_chapter'
    template_name = 'writer/chapter.html'


class WriterChapterPreviewUpdateView(LoginRequiredMixin, PicturesAndTextAsElementsMixin, UpdateView):
    form_class = ChapterPublishForm
    model = Chapter
    pk_url_kwarg = 'pk_chapter'
    template_name = 'writer/chapter-preview.html'

    def form_valid(self, form):
        chapter = self.object
        if chapter.published:
            form.instance.published = False
        else:
            form.instance.published = True
        return super().form_valid(form)

    def get_success_url(self):
        pk_chapter = self.kwargs.get('pk_chapter')
        chapter = Chapter.objects.get(pk = pk_chapter)
        pk_book = chapter.book.pk
        return reverse('writer:book',
            kwargs={
                'slug_book': self.kwargs.get("slug_book"),
                'pk_book': pk_book,
            }
        )


class WriterTemplateView(LoginRequiredMixin, TemplateView):
    template_name = 'writer/writer.html'

class GetBackToChapterMixin():

    def get_success_url(self):
        return reverse('writer:chapter',
            kwargs={
                'slug_book': self.kwargs.get("slug_book"),
                'slug_chapter': self.kwargs.get("slug_chapter"),
                'pk_chapter': self.kwargs.get("pk_chapter"),
            }
        )

class WriterPictureCreateView(LoginRequiredMixin, GetBackToChapterMixin, CreateView):
    model = Picture
    form_class = PictureForm
    template_name = 'writer/picture-create.html'

    def form_valid(self, form):
        self.chapter = Chapter.objects.get(pk = self.kwargs.get('pk_chapter'))
        form.instance.chapter = self.chapter
        return super().form_valid(form)


class WriterPictureDeleteView(LoginRequiredMixin, GetBackToChapterMixin, DeleteView):
    context_object_name = 'picture'
    form_class = PictureForm
    model = Picture
    pk_url_kwarg = 'pk_picture'
    template_name = 'writer/picture-delete.html'


class WriterPictureUpdateView(LoginRequiredMixin, GetBackToChapterMixin, UpdateView):
    model = Picture
    form_class = PictureForm
    pk_url_kwarg = 'pk_picture'
    template_name = 'writer/picture-update.html'

class WriterTextCreateView(LoginRequiredMixin, GetBackToChapterMixin, CreateView):
    model = Text
    form_class = TextForm
    template_name = "writer/add-text.html"

    def form_valid(self, form):
        self.chapter = Chapter.objects.get(pk = self.kwargs.get('pk_chapter'))
        form.instance.chapter = self.chapter
        return super().form_valid(form)


    def get_context_data(self, **kwargs):
        """Insert the single object into the context dict."""
        context = {}

        if self.object:
            context['object'] = self.object
            context['chapter'] = self.chapter
            context_object_name = self.get_context_object_name(self.object)
            if context_object_name:
                context[context_object_name] = self.object
        context.update(kwargs)
        return super().get_context_data(**context)


class WriterTextDeleteView(LoginRequiredMixin, GetBackToChapterMixin, DeleteView):
    form_class = TextForm
    model = Text
    pk_url_kwarg = 'pk_text'
    template_name = "writer/text-delete.html"


class WriterTextUpdateView(LoginRequiredMixin, GetBackToChapterMixin, UpdateView):
    form_class = TextForm
    model = Text
    pk_url_kwarg = 'pk_text'
    template_name = "writer/text-update.html"

tryread/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

tryread/templates/_nav2.html
<div class="py-3">
  <nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
    <a class="navbar-brand" href="{% url 'home:home' %}">Tryread</a>
    <button class="navbar-toggler navbar-toggler-right border-white" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'home:home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'about' %}">About</a>
        </li>
        {% if request.user.is_authenticated %}
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">My Profile</a>
          </li>
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a class="nav-link" href="{% url 'account_logout' %}">Sign Out</a>
          </li>
        {% else %}
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
          </li>
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">Sign In</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>
</div>

tryread/templates/base-danny.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Tryread{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}
    
    <!-- Latest compiled and minified Bootstrap 4 beta CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    

    <!-- Your stuff: Third-party CSS libraries go here -->
    
    <!-- This file stores project-specific CSS -->
    
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    
    
    {% endblock %}

  </head>

  <body>

    <div class="m-b-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">Tryread</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      
      <!-- Required by Bootstrap v4 beta -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->
      

      <!-- place project specific Javascript in this file -->
      
      <script src="{% static 'js/project.js' %}"></script>
      

    {% endblock javascript %}
  </body>
</html>
 

tryread/templates/base-for-all.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Tryread{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    {% block css %}

    <!-- Latest compiled and minified Bootstrap 4 beta CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">


    <!-- Your stuff: Third-party CSS libraries go here -->
    <link href='https://fonts.googleapis.com/css?family=Trocchi' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

    <!-- This file stores project-specific CSS -->

    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    <link href="{% static 'css/tryread.css' %}" rel="stylesheet">



    {% endblock %}

  </head>

  <body>
    {% block main %}

    {% endblock %}


    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}

      <!-- Required by Bootstrap v4 beta -->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->


      <!-- place project specific Javascript in this file -->

      <script src="{% static 'js/project.js' %}"></script>


    {% endblock javascript %}
  </body>
</html>

tryread/templates/base-my.html
{% extends "base-for-all.html" %}
{% load static i18n %}
{% block main %}

  {% if messages %}
    <div class="container">
      {% for message in messages %}
        <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
      {% endfor %}
    </div>
  {% endif %}


  {% include "_nav2.html" %}

  {% block content %}
    <p>Use this document as a way to quick start any new project.</p>
  {% endblock content %}



  {% block modal %}{% endblock modal %}

{% endblock main %}

tryread/templates/base-with-no-nav.html
{% extends "base.html" %}
{% load static i18n %}
{% block main %}

  {% if messages %}
    <div class="container">
      {% for message in messages %}
        <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
      {% endfor %}
    </div>
  {% endif %}



  {% block content %}
    <p>Use this document as a way to quick start any new project.</p>
  {% endblock content %}



  {% block modal %}{% endblock modal %}

{% endblock main %}

tryread/templates/base.html
{% extends "base-for-all.html" %}
{% load static i18n %}
{% block main %}

  {% if messages %}
    <div class="container">
      {% for message in messages %}
        <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
      {% endfor %}
    </div>
  {% endif %}


  {% include "_nav2.html" %}
  <br><br>
  <div class="container">
    {% block content %}
      <p>Use this document as a way to quick start any new project.</p>
    {% endblock content %}
  </div>



  {% block modal %}{% endblock modal %}

{% endblock main %}